import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter } from 'react-router-dom';
import React from 'react';

// Mock supabase
vi.mock('@/integrations/supabase/client', () => ({
  supabase: {
    from: vi.fn(() => ({
      select: vi.fn(() => ({
        eq: vi.fn(() => ({
          order: vi.fn(() => Promise.resolve({ data: [], error: null })),
          maybeSingle: vi.fn(() => Promise.resolve({ data: null, error: null })),
        })),
      })),
      insert: vi.fn(() => ({
        select: vi.fn(() => ({
          single: vi.fn(() => Promise.resolve({ data: { id: 'test-id' }, error: null })),
        })),
      })),
      update: vi.fn(() => ({
        eq: vi.fn(() => ({
          select: vi.fn(() => ({
            single: vi.fn(() => Promise.resolve({ data: { id: 'test-id' }, error: null })),
          })),
        })),
      })),
      delete: vi.fn(() => ({
        eq: vi.fn(() => Promise.resolve({ error: null })),
      })),
    })),
    auth: {
      getSession: vi.fn(() => Promise.resolve({ data: { session: null }, error: null })),
      onAuthStateChange: vi.fn(() => ({ data: { subscription: { unsubscribe: vi.fn() } } })),
    },
  },
}));

// Mock useAuth
vi.mock('@/hooks/useAuth', () => ({
  useAuth: () => ({
    user: { id: 'test-user-id', email: 'test@example.com' },
    loading: false,
  }),
}));

// Mock toast
vi.mock('sonner', () => ({
  toast: {
    success: vi.fn(),
    error: vi.fn(),
  },
}));

const createWrapper = () => {
  const queryClient = new QueryClient({
    defaultOptions: {
      queries: { retry: false },
      mutations: { retry: false },
    },
  });

  return ({ children }: { children: React.ReactNode }) => (
    <QueryClientProvider client={queryClient}>
      <BrowserRouter>{children}</BrowserRouter>
    </QueryClientProvider>
  );
};

describe('useInvoices', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('Invoice calculation logic', () => {
    it('calculates tax at 10%', () => {
      const items = [
        { description: 'Item 1', quantity: 2, unit_price: 10000 },
        { description: 'Item 2', quantity: 1, unit_price: 5000 },
      ];

      const amount = items.reduce((sum, item) => sum + item.quantity * item.unit_price, 0);
      const taxAmount = Math.floor(amount * 0.1);
      const totalAmount = amount + taxAmount;

      expect(amount).toBe(25000);
      expect(taxAmount).toBe(2500);
      expect(totalAmount).toBe(27500);
    });

    it('handles empty items array', () => {
      const items: { quantity: number; unit_price: number }[] = [];

      const amount = items.reduce((sum, item) => sum + item.quantity * item.unit_price, 0);
      const taxAmount = Math.floor(amount * 0.1);

      expect(amount).toBe(0);
      expect(taxAmount).toBe(0);
    });

    it('handles decimal quantities', () => {
      const items = [
        { description: 'Hourly work', quantity: 1.5, unit_price: 10000 },
      ];

      const amount = items.reduce((sum, item) => sum + item.quantity * item.unit_price, 0);

      expect(amount).toBe(15000);
    });
  });

  describe('Invoice status update logic', () => {
    it('sets paid_date when status is paid', () => {
      const status = 'paid';
      const updateData: { status: string; paid_date?: string } = { status };

      if (status === 'paid') {
        updateData.paid_date = new Date().toISOString().split('T')[0];
      }

      expect(updateData.paid_date).toBeDefined();
      expect(updateData.paid_date).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    });

    it('does not set paid_date for draft status', () => {
      const status = 'draft';
      const updateData: { status: string; paid_date?: string } = { status };

      if (status === 'paid') {
        updateData.paid_date = new Date().toISOString().split('T')[0];
      }

      expect(updateData.paid_date).toBeUndefined();
    });

    it('does not set paid_date for sent status', () => {
      const status = 'sent';
      const updateData: { status: string; paid_date?: string } = { status };

      if (status === 'paid') {
        updateData.paid_date = new Date().toISOString().split('T')[0];
      }

      expect(updateData.paid_date).toBeUndefined();
    });
  });

  describe('Invoice number generation', () => {
    it('generates proper invoice number format', () => {
      // Invoice numbers are generated by DB trigger, but we can test the expected format
      const mockInvoiceNumber = 'INV-2024-0001';
      expect(mockInvoiceNumber).toMatch(/^INV-\d{4}-\d{4}$/);
    });
  });

  describe('Invoice validation', () => {
    it('requires title', () => {
      const input = {
        title: '',
        due_date: '2024-12-31',
        items: [],
      };

      expect(input.title).toBe('');
      expect(input.title.length).toBe(0);
    });

    it('requires due_date', () => {
      const input = {
        title: 'Test Invoice',
        due_date: '2024-12-31',
        items: [],
      };

      expect(input.due_date).toBeDefined();
      expect(new Date(input.due_date)).toBeInstanceOf(Date);
    });

    it('validates due_date is not in past', () => {
      const futureDate = new Date();
      futureDate.setMonth(futureDate.getMonth() + 1);
      const dueDateStr = futureDate.toISOString().split('T')[0];

      expect(new Date(dueDateStr) > new Date()).toBe(true);
    });
  });
});

describe('Invoice item calculations', () => {
  it('calculates item amount correctly', () => {
    const item = {
      description: 'Test item',
      quantity: 3,
      unit_price: 1000,
    };

    const amount = item.quantity * item.unit_price;
    expect(amount).toBe(3000);
  });

  it('handles zero quantity', () => {
    const item = {
      description: 'Test item',
      quantity: 0,
      unit_price: 1000,
    };

    const amount = item.quantity * item.unit_price;
    expect(amount).toBe(0);
  });

  it('handles zero unit price', () => {
    const item = {
      description: 'Free item',
      quantity: 5,
      unit_price: 0,
    };

    const amount = item.quantity * item.unit_price;
    expect(amount).toBe(0);
  });

  it('calculates multiple items total', () => {
    const items = [
      { quantity: 2, unit_price: 1000 },
      { quantity: 3, unit_price: 2000 },
      { quantity: 1, unit_price: 5000 },
    ];

    const total = items.reduce((sum, item) => sum + item.quantity * item.unit_price, 0);
    expect(total).toBe(13000); // 2000 + 6000 + 5000
  });
});
