name: Deploy to Fly.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-totono-api-prod
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only --app totono-api-prod --wait-timeout=120
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
