import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import type { 
  Account, 
  JournalEntry, 
  JournalEntryLine, 
  FiscalPeriod, 
  FixedAsset,
  ExpenseClaim,
  TaxSettings,
  AccountType,
  JournalSourceType
} from '@/types/accounting';
import { defaultAccounts } from '@/types/accounting';

// Accounts
export function useAccounts() {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['accounts', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('accounts')
        .select('*')
        .order('account_code');
      
      if (error) throw error;
      return data as Account[];
    },
    enabled: !!user,
  });
}

export function useInitializeAccounts() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async () => {
      if (!user) throw new Error('Not authenticated');
      
      const accountsToInsert = defaultAccounts.map(acc => ({
        ...acc,
        user_id: user.id,
      }));
      
      const { data, error } = await supabase
        .from('accounts')
        .insert(accountsToInsert)
        .select();
      
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['accounts'] });
    },
  });
}

export function useCreateAccount() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (account: {
      account_code: string;
      account_name: string;
      account_type: AccountType;
      parent_account_id?: string;
    }) => {
      if (!user) throw new Error('Not authenticated');
      
      const { data, error } = await supabase
        .from('accounts')
        .insert({
          ...account,
          user_id: user.id,
        })
        .select()
        .single();
      
      if (error) throw error;
      return data as Account;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['accounts'] });
    },
  });
}

// Journal Entries
export function useJournalEntries(fiscalPeriodId?: string) {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['journal-entries', user?.id, fiscalPeriodId],
    queryFn: async () => {
      let query = supabase
        .from('journal_entries')
        .select(`
          *,
          journal_entry_lines (
            *,
            accounts:account_id (*)
          )
        `)
        .order('entry_date', { ascending: false });
      
      if (fiscalPeriodId) {
        query = query.eq('fiscal_period_id', fiscalPeriodId);
      }
      
      const { data, error } = await query;
      
      if (error) throw error;
      return data.map(entry => ({
        ...entry,
        lines: entry.journal_entry_lines?.map((line: any) => ({
          ...line,
          account: line.accounts,
        })),
      })) as JournalEntry[];
    },
    enabled: !!user,
  });
}

export function useJournalEntry(id: string) {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['journal-entry', id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('journal_entries')
        .select(`
          *,
          journal_entry_lines (
            *,
            accounts:account_id (*)
          )
        `)
        .eq('id', id)
        .single();
      
      if (error) throw error;
      return {
        ...data,
        lines: data.journal_entry_lines?.map((line: any) => ({
          ...line,
          account: line.accounts,
        })),
      } as JournalEntry;
    },
    enabled: !!user && !!id,
  });
}

interface CreateJournalEntryInput {
  entry_date: string;
  description?: string;
  source_type?: JournalSourceType;
  source_id?: string;
  fiscal_period_id?: string;
  lines: {
    account_id: string;
    debit_amount: number;
    credit_amount: number;
    description?: string;
  }[];
}

export function useCreateJournalEntry() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (input: CreateJournalEntryInput) => {
      if (!user) throw new Error('Not authenticated');
      
      // Validate balance
      const totalDebit = input.lines.reduce((sum, l) => sum + l.debit_amount, 0);
      const totalCredit = input.lines.reduce((sum, l) => sum + l.credit_amount, 0);
      if (Math.abs(totalDebit - totalCredit) > 0.01) {
        throw new Error('借方と貸方の合計が一致しません');
      }
      
      // Create journal entry
      const insertData = {
        user_id: user.id,
        entry_number: '', // Auto-generated by trigger
        entry_date: input.entry_date,
        description: input.description,
        source_type: input.source_type || 'manual',
        source_id: input.source_id,
        fiscal_period_id: input.fiscal_period_id,
      };
      
      const { data: entry, error: entryError } = await supabase
        .from('journal_entries')
        .insert(insertData as any)
        .select()
        .single();
      
      if (entryError) throw entryError;
      
      // Create lines
      const { error: linesError } = await supabase
        .from('journal_entry_lines')
        .insert(
          input.lines.map(line => ({
            journal_entry_id: entry.id,
            account_id: line.account_id,
            debit_amount: line.debit_amount,
            credit_amount: line.credit_amount,
            description: line.description,
          }))
        );
      
      if (linesError) throw linesError;
      
      return entry as JournalEntry;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['journal-entries'] });
    },
  });
}

export function useDeleteJournalEntry() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('journal_entries')
        .delete()
        .eq('id', id);
      
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['journal-entries'] });
    },
  });
}

// Fiscal Periods
export function useFiscalPeriods() {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['fiscal-periods', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('fiscal_periods')
        .select('*')
        .order('start_date', { ascending: false });
      
      if (error) throw error;
      return data as FiscalPeriod[];
    },
    enabled: !!user,
  });
}

export function useCreateFiscalPeriod() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (period: {
      period_name: string;
      start_date: string;
      end_date: string;
    }) => {
      if (!user) throw new Error('Not authenticated');
      
      const { data, error } = await supabase
        .from('fiscal_periods')
        .insert({
          ...period,
          user_id: user.id,
        })
        .select()
        .single();
      
      if (error) throw error;
      return data as FiscalPeriod;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['fiscal-periods'] });
    },
  });
}

// Fixed Assets
export function useFixedAssets() {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['fixed-assets', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('fixed_assets')
        .select('*')
        .order('acquisition_date', { ascending: false });
      
      if (error) throw error;
      return data as FixedAsset[];
    },
    enabled: !!user,
  });
}

export function useCreateFixedAsset() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (asset: Omit<FixedAsset, 'id' | 'user_id' | 'created_at' | 'updated_at'>) => {
      if (!user) throw new Error('Not authenticated');
      
      const { data, error } = await supabase
        .from('fixed_assets')
        .insert({
          ...asset,
          user_id: user.id,
        })
        .select()
        .single();
      
      if (error) throw error;
      return data as FixedAsset;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['fixed-assets'] });
    },
  });
}

// Expense Claims
export function useExpenseClaims() {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['expense-claims', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('expense_claims')
        .select(`
          *,
          expense_items (
            *,
            accounts:account_id (*)
          )
        `)
        .order('claim_date', { ascending: false });
      
      if (error) throw error;
      return data.map(claim => ({
        ...claim,
        items: claim.expense_items?.map((item: any) => ({
          ...item,
          account: item.accounts,
        })),
      })) as ExpenseClaim[];
    },
    enabled: !!user,
  });
}

export function useCreateExpenseClaim() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (claim: {
      claim_date: string;
      claimant_name?: string;
      items: {
        expense_date: string;
        account_id?: string;
        description: string;
        amount: number;
        vendor_name?: string;
      }[];
    }) => {
      if (!user) throw new Error('Not authenticated');
      
      const total_amount = claim.items.reduce((sum, item) => sum + item.amount, 0);
      
      const { data: expenseClaim, error: claimError } = await supabase
        .from('expense_claims')
        .insert({
          user_id: user.id,
          claim_number: '', // Auto-generated
          claim_date: claim.claim_date,
          claimant_name: claim.claimant_name,
          total_amount,
        })
        .select()
        .single();
      
      if (claimError) throw claimError;
      
      const { error: itemsError } = await supabase
        .from('expense_items')
        .insert(
          claim.items.map(item => ({
            expense_claim_id: expenseClaim.id,
            expense_date: item.expense_date,
            account_id: item.account_id,
            description: item.description,
            amount: item.amount,
            vendor_name: item.vendor_name,
          }))
        );
      
      if (itemsError) throw itemsError;
      
      return expenseClaim as ExpenseClaim;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['expense-claims'] });
    },
  });
}

// Tax Settings
export function useTaxSettings() {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['tax-settings', user?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('tax_settings')
        .select('*')
        .maybeSingle();
      
      if (error) throw error;
      return data as TaxSettings | null;
    },
    enabled: !!user,
  });
}

export function useUpsertTaxSettings() {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (settings: Partial<TaxSettings>) => {
      if (!user) throw new Error('Not authenticated');
      
      const { data, error } = await supabase
        .from('tax_settings')
        .upsert({
          ...settings,
          user_id: user.id,
        })
        .select()
        .single();
      
      if (error) throw error;
      return data as TaxSettings;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tax-settings'] });
    },
  });
}

// Financial Statements Calculations
export function useTrialBalance(startDate: string, endDate: string) {
  const { user } = useAuth();
  
  return useQuery({
    queryKey: ['trial-balance', user?.id, startDate, endDate],
    queryFn: async () => {
      const { data: entries, error } = await supabase
        .from('journal_entries')
        .select(`
          *,
          journal_entry_lines (
            *,
            accounts:account_id (*)
          )
        `)
        .gte('entry_date', startDate)
        .lte('entry_date', endDate);
      
      if (error) throw error;
      
      // Calculate balances by account
      const balances: Record<string, { 
        account: Account; 
        debit: number; 
        credit: number; 
      }> = {};
      
      entries.forEach((entry: any) => {
        entry.journal_entry_lines?.forEach((line: any) => {
          const accountId = line.account_id;
          if (!balances[accountId]) {
            balances[accountId] = {
              account: line.accounts,
              debit: 0,
              credit: 0,
            };
          }
          balances[accountId].debit += Number(line.debit_amount) || 0;
          balances[accountId].credit += Number(line.credit_amount) || 0;
        });
      });
      
      return Object.values(balances).sort((a, b) => 
        a.account.account_code.localeCompare(b.account.account_code)
      );
    },
    enabled: !!user && !!startDate && !!endDate,
  });
}

export function useGeneralLedger(accountId: string, startDate: string, endDate: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['general-ledger', accountId, startDate, endDate],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('journal_entry_lines')
        .select(`
          *,
          journal_entries!inner (
            id,
            entry_number,
            entry_date,
            description
          ),
          accounts:account_id (*)
        `)
        .eq('account_id', accountId)
        .gte('journal_entries.entry_date', startDate)
        .lte('journal_entries.entry_date', endDate)
        .order('journal_entries(entry_date)', { ascending: true });

      if (error) throw error;

      let runningBalance = 0;
      return data.map((line: any) => {
        runningBalance += (Number(line.debit_amount) || 0) - (Number(line.credit_amount) || 0);
        return {
          ...line,
          journal_entry: line.journal_entries,
          account: line.accounts,
          running_balance: runningBalance,
        };
      });
    },
    enabled: !!user && !!accountId && !!startDate && !!endDate,
  });
}

// ===== 消費税計算 =====
// Note: tax_calculations table not yet created - these hooks return empty/mock data
export function useTaxCalculations(_fiscalPeriodId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['tax-calculations', user?.id, _fiscalPeriodId],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as Array<{
        id: string;
        fiscal_period_id: string;
        calculation_date: string;
        sales_taxable: number;
        sales_tax_collected: number;
        purchases_taxable: number;
        purchases_tax_paid: number;
        tax_payable: number;
        tax_refundable: number;
        net_tax_liability: number;
      }>;
    },
    enabled: !!user,
  });
}

export function useCalculateTax() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ fiscalPeriodId, startDate, endDate }: {
      fiscalPeriodId: string;
      startDate: string;
      endDate: string;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Get journal entries for the period
      const { data: entries, error: entriesError } = await supabase
        .from('journal_entries')
        .select(`
          *,
          journal_entry_lines (
            *,
            accounts:account_id (*)
          )
        `)
        .gte('entry_date', startDate)
        .lte('entry_date', endDate);

      if (entriesError) throw entriesError;

      // Calculate tax amounts
      let salesTaxable = 0;
      let purchasesTaxable = 0;

      entries?.forEach((entry: any) => {
        entry.journal_entry_lines?.forEach((line: any) => {
          const account = line.accounts;
          if (account?.account_type === 'revenue') {
            salesTaxable += Number(line.credit_amount) || 0;
          } else if (account?.account_type === 'expense') {
            purchasesTaxable += Number(line.debit_amount) || 0;
          }
        });
      });

      // Default 10% consumption tax
      const salesTaxCollected = Math.round(salesTaxable * 0.1);
      const purchasesTaxPaid = Math.round(purchasesTaxable * 0.1);
      const taxPayable = salesTaxCollected;
      const taxRefundable = purchasesTaxPaid;
      const netTaxLiability = taxPayable - taxRefundable;

      // Return calculated data (table not yet created)
      return {
        id: crypto.randomUUID(),
        fiscal_period_id: fiscalPeriodId,
        calculation_date: new Date().toISOString().split('T')[0],
        sales_taxable: salesTaxable,
        sales_tax_collected: salesTaxCollected,
        purchases_taxable: purchasesTaxable,
        purchases_tax_paid: purchasesTaxPaid,
        tax_payable: taxPayable,
        tax_refundable: taxRefundable,
        net_tax_liability: netTaxLiability,
      };
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['tax-calculations'] });
    },
  });
}

// ===== 銀行口座 =====
// Note: bank_accounts table not yet created - these hooks return empty/mock data
interface BankAccount {
  id: string;
  bank_name: string;
  branch_name?: string;
  account_number: string;
  account_type?: 'ordinary' | 'checking' | 'savings';
  linked_account_id?: string;
  user_id: string;
}

export function useBankAccounts() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['bank-accounts', user?.id],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as BankAccount[];
    },
    enabled: !!user,
  });
}

export function useCreateBankAccount() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (account: {
      bank_name: string;
      branch_name?: string;
      account_number: string;
      account_type?: 'ordinary' | 'checking' | 'savings';
      linked_account_id?: string;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      return {
        id: crypto.randomUUID(),
        ...account,
        user_id: user.id,
      } as BankAccount;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bank-accounts'] });
    },
  });
}

// ===== 銀行取引明細 =====
// Note: bank_transactions table not yet created - these hooks return empty/mock data
interface BankTransaction {
  id: string;
  bank_account_id: string;
  transaction_date: string;
  description: string;
  amount: number;
  balance_after: number;
  reference_number?: string;
  matched_journal_entry_id?: string;
  status?: string;
  user_id: string;
}

export function useBankTransactions(_bankAccountId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['bank-transactions', user?.id, _bankAccountId],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as BankTransaction[];
    },
    enabled: !!user,
  });
}

export function useImportBankTransactions() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ bankAccountId, transactions }: {
      bankAccountId: string;
      transactions: {
        transaction_date: string;
        description: string;
        amount: number;
        balance_after: number;
        reference_number?: string;
      }[];
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      return transactions.map(t => ({
        id: crypto.randomUUID(),
        ...t,
        user_id: user.id,
        bank_account_id: bankAccountId,
      })) as BankTransaction[];
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bank-transactions'] });
    },
  });
}

export function useMatchBankTransaction() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ transactionId, journalEntryId }: {
      transactionId: string;
      journalEntryId: string;
    }) => {
      // Return mock data (table not yet created)
      return {
        id: transactionId,
        matched_journal_entry_id: journalEntryId,
        status: 'matched',
      } as Partial<BankTransaction>;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['bank-transactions'] });
    },
  });
}

// ===== 仕訳テンプレート =====
// Note: journal_templates table not yet created - these hooks return empty/mock data
interface JournalTemplateLine {
  id: string;
  template_id: string;
  account_id: string;
  debit_amount: number;
  credit_amount: number;
  description?: string;
  account?: Account;
}

interface JournalTemplate {
  id: string;
  template_name: string;
  description?: string;
  is_recurring?: boolean;
  recurrence_pattern?: string;
  user_id: string;
  lines?: JournalTemplateLine[];
}

export function useJournalTemplates() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['journal-templates', user?.id],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as JournalTemplate[];
    },
    enabled: !!user,
  });
}

export function useCreateJournalTemplate() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: {
      template_name: string;
      description?: string;
      is_recurring?: boolean;
      recurrence_pattern?: string;
      lines: {
        account_id: string;
        debit_amount: number;
        credit_amount: number;
        description?: string;
      }[];
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      const templateId = crypto.randomUUID();
      return {
        id: templateId,
        template_name: input.template_name,
        description: input.description,
        is_recurring: input.is_recurring,
        recurrence_pattern: input.recurrence_pattern,
        user_id: user.id,
        lines: input.lines.map(line => ({
          id: crypto.randomUUID(),
          template_id: templateId,
          ...line,
        })),
      } as JournalTemplate;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['journal-templates'] });
    },
  });
}

export function useApplyJournalTemplate() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ templateId: _templateId, entryDate, description }: {
      templateId: string;
      entryDate: string;
      description?: string;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Create journal entry (templates table not yet created, so create empty entry)
      const { data: entry, error: entryError } = await supabase
        .from('journal_entries')
        .insert({
          user_id: user.id,
          entry_number: '',
          entry_date: entryDate,
          description: description || 'テンプレートから作成',
          source_type: 'manual',
        })
        .select()
        .single();

      if (entryError) throw entryError;

      return entry as JournalEntry;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['journal-entries'] });
    },
  });
}

// ===== コストセンター（部門） =====
// Note: cost_centers table not yet created - these hooks return empty/mock data
interface CostCenter {
  id: string;
  code: string;
  name: string;
  parent_id?: string;
  manager_name?: string;
  is_active?: boolean;
  user_id: string;
}

export function useCostCenters() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['cost-centers', user?.id],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as CostCenter[];
    },
    enabled: !!user,
  });
}

export function useCreateCostCenter() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (center: {
      code: string;
      name: string;
      parent_id?: string;
      manager_name?: string;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      return {
        id: crypto.randomUUID(),
        ...center,
        user_id: user.id,
      } as CostCenter;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cost-centers'] });
    },
  });
}

// ===== 買掛金 =====
// Note: accounts_payable table not yet created - these hooks return empty/mock data
interface AccountPayable {
  id: string;
  vendor_id?: string;
  vendor_name: string;
  invoice_number: string;
  invoice_date: string;
  due_date: string;
  amount: number;
  balance: number;
  paid_amount: number;
  status: string;
  user_id: string;
  journal_entry_id?: string;
}

export function useAccountsPayable() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['accounts-payable', user?.id],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as AccountPayable[];
    },
    enabled: !!user,
  });
}

export function useAccountsPayableAging() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['accounts-payable-aging', user?.id],
    queryFn: async () => {
      // Return empty aging data (table not yet created)
      return {
        current: 0,
        days1to30: 0,
        days31to60: 0,
        days61to90: 0,
        over90: 0,
        total: 0,
        items: [] as AccountPayable[],
      };
    },
    enabled: !!user,
  });
}

export function useCreateAccountsPayable() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (payable: {
      vendor_id?: string;
      vendor_name: string;
      invoice_number: string;
      invoice_date: string;
      due_date: string;
      amount: number;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      return {
        id: crypto.randomUUID(),
        ...payable,
        balance: payable.amount,
        paid_amount: 0,
        status: 'open',
        user_id: user.id,
      } as AccountPayable;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['accounts-payable'] });
      queryClient.invalidateQueries({ queryKey: ['accounts-payable-aging'] });
    },
  });
}

// ===== 予算 =====
// Note: budgets table not yet created - these hooks return empty/mock data
interface Budget {
  id: string;
  fiscal_period_id: string;
  account_id: string;
  cost_center_id?: string;
  budget_amount: number;
  notes?: string;
  user_id: string;
}

export function useBudgets(_fiscalPeriodId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['budgets', user?.id, _fiscalPeriodId],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as Budget[];
    },
    enabled: !!user,
  });
}

export function useBudgetVsActual(_fiscalPeriodId: string, startDate: string, endDate: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['budget-vs-actual', _fiscalPeriodId, startDate, endDate],
    queryFn: async () => {
      // Return empty data (budgets table not yet created)
      return [] as Array<Budget & { actual: number; variance: number; variancePercent: number }>;
    },
    enabled: !!user && !!_fiscalPeriodId && !!startDate && !!endDate,
  });
}

export function useCreateBudget() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (budget: {
      fiscal_period_id: string;
      account_id: string;
      cost_center_id?: string;
      budget_amount: number;
      notes?: string;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      return {
        id: crypto.randomUUID(),
        ...budget,
        user_id: user.id,
      } as Budget;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['budgets'] });
    },
  });
}

// ===== 為替レート =====
// Note: exchange_rates table not yet created - these hooks return empty/mock data
interface ExchangeRate {
  id: string;
  from_currency: string;
  to_currency: string;
  rate: number;
  effective_date: string;
  user_id: string;
}

export function useExchangeRates() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['exchange-rates', user?.id],
    queryFn: async () => {
      // Table not yet created, return empty array
      return [] as ExchangeRate[];
    },
    enabled: !!user,
  });
}

export function useCreateExchangeRate() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (rate: {
      from_currency: string;
      to_currency: string;
      rate: number;
      effective_date: string;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      return {
        id: crypto.randomUUID(),
        ...rate,
        user_id: user.id,
      } as ExchangeRate;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['exchange-rates'] });
    },
  });
}

// ===== 決算処理 =====
// Note: period_close_processes table not yet created - these hooks return empty/mock data
interface PeriodCloseProcess {
  id: string;
  fiscal_period_id: string;
  step: 'draft' | 'adjustments' | 'tax_calculation' | 'closing_entries' | 'completed';
  started_at: string;
  completed_at?: string;
  user_id: string;
}

export function usePeriodCloseProcess(_fiscalPeriodId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['period-close', user?.id, _fiscalPeriodId],
    queryFn: async () => {
      // Table not yet created, return null
      return null as PeriodCloseProcess | null;
    },
    enabled: !!user,
  });
}

export function useStartPeriodClose() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (fiscalPeriodId: string) => {
      if (!user) throw new Error('Not authenticated');

      // Return mock data (table not yet created)
      return {
        id: crypto.randomUUID(),
        fiscal_period_id: fiscalPeriodId,
        step: 'draft' as const,
        started_at: new Date().toISOString(),
        user_id: user.id,
      } as PeriodCloseProcess;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['period-close'] });
    },
  });
}

export function useAdvancePeriodClose() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ processId, nextStep }: {
      processId: string;
      nextStep: 'adjustments' | 'tax_calculation' | 'closing_entries' | 'completed';
    }) => {
      // Return mock data (table not yet created)
      return {
        id: processId,
        step: nextStep,
        completed_at: nextStep === 'completed' ? new Date().toISOString() : undefined,
      } as Partial<PeriodCloseProcess>;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['period-close'] });
    },
  });
}

export function useCloseFiscalPeriod() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (fiscalPeriodId: string) => {
      const { data, error } = await supabase
        .from('fiscal_periods')
        .update({
          is_closed: true,
          closed_at: new Date().toISOString(),
        })
        .eq('id', fiscalPeriodId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['fiscal-periods'] });
      queryClient.invalidateQueries({ queryKey: ['period-close'] });
    },
  });
}

// ===== 減価償却自動実行 =====
export function useRunDepreciation() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ fiscalPeriodId, depreciationDate }: {
      fiscalPeriodId: string;
      depreciationDate: string;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Get active fixed assets
      const { data: assets, error: assetsError } = await supabase
        .from('fixed_assets')
        .select('*')
        .eq('is_active', true)
        .is('disposal_date', null);

      if (assetsError) throw assetsError;

      const results: any[] = [];

      for (const asset of assets || []) {
        // Calculate depreciation amount
        let depreciationAmount = 0;
        const acquisitionCost = Number(asset.acquisition_cost);
        const salvageValue = Number(asset.salvage_value) || 0;
        const usefulLife = asset.useful_life_years;
        const currentBookValue = Number(asset.current_book_value);

        if (asset.depreciation_method === 'straight_line') {
          // 定額法
          depreciationAmount = (acquisitionCost - salvageValue) / usefulLife / 12;
        } else {
          // 定率法 (200% declining balance)
          const rate = (2 / usefulLife);
          depreciationAmount = currentBookValue * rate / 12;
        }

        depreciationAmount = Math.min(depreciationAmount, currentBookValue - salvageValue);

        if (depreciationAmount <= 0) continue;

        // Get last accumulated depreciation
        const { data: lastSchedule } = await supabase
          .from('depreciation_schedules')
          .select('accumulated_depreciation')
          .eq('fixed_asset_id', asset.id)
          .order('depreciation_date', { ascending: false })
          .limit(1)
          .single();

        const previousAccumulated = Number(lastSchedule?.accumulated_depreciation) || 0;
        const newAccumulated = previousAccumulated + depreciationAmount;
        const newBookValue = acquisitionCost - newAccumulated;

        // Create depreciation schedule
        const { data: schedule, error: scheduleError } = await supabase
          .from('depreciation_schedules')
          .insert({
            fixed_asset_id: asset.id,
            fiscal_period_id: fiscalPeriodId,
            depreciation_date: depreciationDate,
            depreciation_amount: depreciationAmount,
            accumulated_depreciation: newAccumulated,
            book_value_after: newBookValue,
          })
          .select()
          .single();

        if (scheduleError) throw scheduleError;

        // Update fixed asset book value
        await supabase
          .from('fixed_assets')
          .update({ current_book_value: newBookValue })
          .eq('id', asset.id);

        results.push({ asset, schedule, depreciationAmount });
      }

      return results;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['fixed-assets'] });
      queryClient.invalidateQueries({ queryKey: ['depreciation-schedules'] });
    },
  });
}

export function useDepreciationSchedules(assetId?: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['depreciation-schedules', user?.id, assetId],
    queryFn: async () => {
      let query = supabase
        .from('depreciation_schedules')
        .select('*, fixed_assets(*), fiscal_periods(*)')
        .order('depreciation_date', { ascending: false });

      if (assetId) {
        query = query.eq('fixed_asset_id', assetId);
      }

      const { data, error } = await query;
      if (error) throw error;
      return data;
    },
    enabled: !!user,
  });
}

// ===== キャッシュフロー計算書 =====
export function useCashFlowStatement(startDate: string, endDate: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['cash-flow-statement', user?.id, startDate, endDate],
    queryFn: async () => {
      // Get journal entries for the period
      const { data: entries, error } = await supabase
        .from('journal_entries')
        .select(`
          *,
          journal_entry_lines (
            *,
            accounts:account_id (*)
          )
        `)
        .gte('entry_date', startDate)
        .lte('entry_date', endDate);

      if (error) throw error;

      // Classify cash flows
      const operating: any[] = [];
      const investing: any[] = [];
      const financing: any[] = [];

      let netOperating = 0;
      let netInvesting = 0;
      let netFinancing = 0;

      // Cash account codes
      const cashAccountCodes = ['1000', '1100'];

      entries?.forEach((entry: any) => {
        entry.journal_entry_lines?.forEach((line: any) => {
          const account = line.accounts;
          if (!account) return;

          const cashChange = (Number(line.debit_amount) || 0) - (Number(line.credit_amount) || 0);

          // Only track cash movements
          if (!cashAccountCodes.includes(account.account_code)) return;

          // Classify by source type
          const item = {
            category: 'operating' as 'operating' | 'investing' | 'financing',
            subcategory: entry.source_type || 'その他',
            description: entry.description || account.account_name,
            amount: cashChange,
          };

          switch (entry.source_type) {
            case 'invoice':
            case 'payment':
            case 'expense':
              item.category = 'operating';
              operating.push(item);
              netOperating += cashChange;
              break;
            case 'depreciation':
              item.category = 'investing';
              investing.push(item);
              netInvesting += cashChange;
              break;
            default:
              // Check account type for classification
              if (account.account_code >= '1700' && account.account_code < '2000') {
                // Fixed assets
                item.category = 'investing';
                investing.push(item);
                netInvesting += cashChange;
              } else if (account.account_code >= '2700' && account.account_code < '3000') {
                // Borrowings
                item.category = 'financing';
                financing.push(item);
                netFinancing += cashChange;
              } else if (account.account_code >= '3000' && account.account_code < '4000') {
                // Equity
                item.category = 'financing';
                financing.push(item);
                netFinancing += cashChange;
              } else {
                operating.push(item);
                netOperating += cashChange;
              }
          }
        });
      });

      // Get beginning cash balance
      const { data: beginningData } = await supabase
        .from('journal_entries')
        .select(`
          journal_entry_lines (
            debit_amount,
            credit_amount,
            accounts:account_id (account_code)
          )
        `)
        .lt('entry_date', startDate);

      let beginningCash = 0;
      beginningData?.forEach((entry: any) => {
        entry.journal_entry_lines?.forEach((line: any) => {
          if (cashAccountCodes.includes(line.accounts?.account_code)) {
            beginningCash += (Number(line.debit_amount) || 0) - (Number(line.credit_amount) || 0);
          }
        });
      });

      const netChange = netOperating + netInvesting + netFinancing;
      const endingCash = beginningCash + netChange;

      return {
        period_start: startDate,
        period_end: endDate,
        operating_activities: operating,
        investing_activities: investing,
        financing_activities: financing,
        net_operating: netOperating,
        net_investing: netInvesting,
        net_financing: netFinancing,
        net_change: netChange,
        beginning_cash: beginningCash,
        ending_cash: endingCash,
      };
    },
    enabled: !!user && !!startDate && !!endDate,
  });
}

// ===== 自動仕訳 =====
export function useCreateJournalFromInvoice() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (invoiceId: string) => {
      if (!user) throw new Error('Not authenticated');

      // Get invoice
      const { data: invoice, error: invoiceError } = await supabase
        .from('invoices')
        .select('*')
        .eq('id', invoiceId)
        .single();

      if (invoiceError) throw invoiceError;

      // Get accounts
      const { data: accounts } = await supabase
        .from('accounts')
        .select('*')
        .in('account_code', ['1200', '4000', '2910']); // 売掛金, 売上高, 未払消費税

      const receivablesAccount = accounts?.find(a => a.account_code === '1200');
      const revenueAccount = accounts?.find(a => a.account_code === '4000');
      const taxAccount = accounts?.find(a => a.account_code === '2910');

      if (!receivablesAccount || !revenueAccount) {
        throw new Error('必要な勘定科目が見つかりません');
      }

      const amount = Number(invoice.amount);
      const taxAmount = Number(invoice.tax_amount) || 0;
      const totalAmount = Number(invoice.total_amount);

      // Create journal entry
      const { data: entry, error: entryError } = await supabase
        .from('journal_entries')
        .insert({
          user_id: user.id,
          entry_number: '',
          entry_date: invoice.issue_date,
          description: `請求書 ${invoice.invoice_number}: ${invoice.title}`,
          source_type: 'invoice',
          source_id: invoiceId,
        })
        .select()
        .single();

      if (entryError) throw entryError;

      // Create lines: Debit 売掛金, Credit 売上高 + 消費税
      const lines = [
        {
          journal_entry_id: entry.id,
          account_id: receivablesAccount.id,
          debit_amount: totalAmount,
          credit_amount: 0,
          description: '売掛金',
        },
        {
          journal_entry_id: entry.id,
          account_id: revenueAccount.id,
          debit_amount: 0,
          credit_amount: amount,
          description: '売上高',
        },
      ];

      if (taxAmount > 0 && taxAccount) {
        lines.push({
          journal_entry_id: entry.id,
          account_id: taxAccount.id,
          debit_amount: 0,
          credit_amount: taxAmount,
          description: '消費税',
        });
      }

      const { error: linesError } = await supabase
        .from('journal_entry_lines')
        .insert(lines);

      if (linesError) throw linesError;

      return entry;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['journal-entries'] });
    },
  });
}

export function useCreateJournalFromPayment() {
  const { user } = useAuth();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ payableId: _payableId, paymentDate, amount }: {
      payableId: string;
      paymentDate: string;
      amount: number;
    }) => {
      if (!user) throw new Error('Not authenticated');

      // Get accounts
      const { data: accounts } = await supabase
        .from('accounts')
        .select('*')
        .in('account_code', ['1100', '2000']); // 普通預金, 買掛金

      const cashAccount = accounts?.find(a => a.account_code === '1100');
      const payablesAccount = accounts?.find(a => a.account_code === '2000');

      if (!cashAccount || !payablesAccount) {
        throw new Error('必要な勘定科目が見つかりません');
      }

      // Create journal entry (accounts_payable table not yet created)
      const { data: entry, error: entryError } = await supabase
        .from('journal_entries')
        .insert({
          user_id: user.id,
          entry_number: '',
          entry_date: paymentDate,
          description: '支払処理',
          source_type: 'payment',
          source_id: _payableId,
        })
        .select()
        .single();

      if (entryError) throw entryError;

      // Create lines: Debit 買掛金, Credit 普通預金
      const { error: linesError } = await supabase
        .from('journal_entry_lines')
        .insert([
          {
            journal_entry_id: entry.id,
            account_id: payablesAccount.id,
            debit_amount: amount,
            credit_amount: 0,
            description: '買掛金支払',
          },
          {
            journal_entry_id: entry.id,
            account_id: cashAccount.id,
            debit_amount: 0,
            credit_amount: amount,
            description: '普通預金',
          },
        ]);

      if (linesError) throw linesError;

      return entry as JournalEntry;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['journal-entries'] });
      queryClient.invalidateQueries({ queryKey: ['accounts-payable'] });
    },
  });
}
