import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';
import type { Contract, ContractItem } from '@/types/contract';

export function useContracts() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['contracts', user?.id],
    queryFn: async () => {
      if (!user) return [];
      
      const { data, error } = await supabase
        .from('contracts')
        .select(`
          *,
          client:clients(id, name, email),
          signatures:contract_signatures(*)
        `)
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as Contract[];
    },
    enabled: !!user,
  });
}

export function useContract(id: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['contract', id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('contracts')
        .select(`
          *,
          client:clients(id, name, email),
          signatures:contract_signatures(*)
        `)
        .eq('id', id)
        .single();
      
      if (error) throw error;
      return data as Contract;
    },
    enabled: !!user && !!id,
  });
}

export function useContractItems(contractId: string) {
  return useQuery({
    queryKey: ['contract-items', contractId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('contract_items')
        .select('*')
        .eq('contract_id', contractId)
        .order('item_order', { ascending: true });
      
      if (error) throw error;
      return data as ContractItem[];
    },
    enabled: !!contractId,
  });
}

interface CreateContractInput {
  client_id?: string | null;
  title: string;
  content?: string | null;
  amount?: number;
  tax_amount?: number | null;
  valid_until?: string | null;
  items?: Array<{ title: string; content: string }>;
}

export function useCreateContract() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (input: CreateContractInput) => {
      if (!user) throw new Error('ログインが必要です');

      const taxAmount = input.tax_amount ?? Math.floor((input.amount || 0) * 0.1);
      const totalAmount = (input.amount || 0) + taxAmount;

      const { data: contract, error } = await supabase
        .from('contracts')
        .insert({
          user_id: user.id,
          client_id: input.client_id || null,
          title: input.title,
          content: input.content || null,
          amount: input.amount || 0,
          tax_amount: taxAmount,
          total_amount: totalAmount,
          valid_until: input.valid_until || null,
          contract_number: '', // Auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      // Insert contract items if provided
      if (input.items && input.items.length > 0) {
        const itemsToInsert = input.items.map((item, index) => ({
          contract_id: contract.id,
          title: item.title,
          content: item.content,
          item_order: index + 1,
        }));

        const { error: itemsError } = await supabase
          .from('contract_items')
          .insert(itemsToInsert);

        if (itemsError) throw itemsError;
      }

      return contract;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contracts'] });
      toast.success('契約書を作成しました');
    },
    onError: (error) => {
      toast.error('契約書の作成に失敗しました: ' + error.message);
    },
  });
}

export function useUpdateContract() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...input }: Partial<Contract> & { id: string }) => {
      const { data, error } = await supabase
        .from('contracts')
        .update(input)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['contracts'] });
      queryClient.invalidateQueries({ queryKey: ['contract', data.id] });
      toast.success('契約書を更新しました');
    },
    onError: (error) => {
      toast.error('契約書の更新に失敗しました: ' + error.message);
    },
  });
}

export function useDeleteContract() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from('contracts')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['contracts'] });
      toast.success('契約書を削除しました');
    },
    onError: (error) => {
      toast.error('契約書の削除に失敗しました: ' + error.message);
    },
  });
}
