import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { toast } from 'sonner';
import type { Tables, TablesInsert } from '@/integrations/supabase/types';

type Invoice = Tables<'invoices'>;
type InvoiceItem = Tables<'invoice_items'>;

export function useInvoices() {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['invoices', user?.id],
    queryFn: async () => {
      if (!user) return [];
      
      const { data, error } = await supabase
        .from('invoices')
        .select(`
          *,
          client:clients(id, name, email)
        `)
        .eq('user_id', user.id)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data;
    },
    enabled: !!user,
  });
}

export function useInvoice(id: string) {
  const { user } = useAuth();

  return useQuery({
    queryKey: ['invoice', id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('invoices')
        .select(`
          *,
          client:clients(id, name, email, address, phone),
          items:invoice_items(*)
        `)
        .eq('id', id)
        .maybeSingle();
      
      if (error) throw error;
      return data;
    },
    enabled: !!user && !!id,
  });
}

interface CreateInvoiceInput {
  title: string;
  client_id?: string | null;
  description?: string | null;
  due_date: string;
  items: {
    description: string;
    quantity: number;
    unit_price: number;
  }[];
}

export function useCreateInvoice() {
  const queryClient = useQueryClient();
  const { user } = useAuth();

  return useMutation({
    mutationFn: async (input: CreateInvoiceInput) => {
      if (!user) throw new Error('ログインが必要です');

      // Calculate totals
      const amount = input.items.reduce((sum, item) => sum + item.quantity * item.unit_price, 0);
      const taxAmount = Math.floor(amount * 0.1); // 10% tax
      const totalAmount = amount + taxAmount;

      // Create invoice
      const { data: invoice, error: invoiceError } = await supabase
        .from('invoices')
        .insert({
          user_id: user.id,
          title: input.title,
          client_id: input.client_id,
          description: input.description,
          due_date: input.due_date,
          amount,
          tax_amount: taxAmount,
          total_amount: totalAmount,
          invoice_number: '', // Will be generated by trigger
        })
        .select()
        .single();

      if (invoiceError) throw invoiceError;

      // Create invoice items
      if (input.items.length > 0) {
        const { error: itemsError } = await supabase
          .from('invoice_items')
          .insert(
            input.items.map(item => ({
              invoice_id: invoice.id,
              description: item.description,
              quantity: item.quantity,
              unit_price: item.unit_price,
              amount: item.quantity * item.unit_price,
            }))
          );

        if (itemsError) throw itemsError;
      }

      return invoice;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      toast.success('請求書を作成しました');
    },
    onError: (error) => {
      toast.error('請求書の作成に失敗しました: ' + error.message);
    },
  });
}

export function useUpdateInvoiceStatus() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, status }: { id: string; status: Invoice['status'] }) => {
      const updateData: Partial<Invoice> = { status };
      
      if (status === 'paid') {
        updateData.paid_date = new Date().toISOString().split('T')[0];
      }

      const { data, error } = await supabase
        .from('invoices')
        .update(updateData)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      queryClient.invalidateQueries({ queryKey: ['invoice', data.id] });
      toast.success('請求書のステータスを更新しました');
    },
    onError: (error) => {
      toast.error('ステータスの更新に失敗しました: ' + error.message);
    },
  });
}

export function useDeleteInvoice() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string) => {
      // Delete items first
      await supabase.from('invoice_items').delete().eq('invoice_id', id);
      
      const { error } = await supabase
        .from('invoices')
        .delete()
        .eq('id', id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      toast.success('請求書を削除しました');
    },
    onError: (error) => {
      toast.error('請求書の削除に失敗しました: ' + error.message);
    },
  });
}
